'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Course
    Public Property Course_ID As Integer
    Public Property Course_Name As String
    Public Property Description As String

    Public Overridable Property Registrations As ICollection(Of Registration) = New HashSet(Of Registration)

End Class
