'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Registration
    Public Property Registration_ID As Integer
    Public Property [date] As Nullable(Of Date)
    Public Property Student_ID As Nullable(Of Integer)
    Public Property Course_ID As Nullable(Of Integer)
    Public Property Subject_ID As Nullable(Of Integer)
    Public Property School_year_ID As Nullable(Of Integer)

    Public Overridable Property Course As Course
    Public Overridable Property School_year As School_year
    Public Overridable Property Student As Student
    Public Overridable Property Subject As Subject

End Class
